---
services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD:-root}
    volumes:
      - ./data:/data/db
    ports:
      - ${MONGO_PORT}:27017

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    restart: on-failure
    environment:
      NGROK_AUTH: ${NGROK_AUTH}
      NGROK_PORT: bot:${TG_WEBHOOK_PORT:-8080}
      NGROK_DEBUG: 1
    ports:
      - 4040:4040

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - ngrok
    environment:
      GS_CREDS: "/opt/app/credentials.json"
      GS_FILE_PREFIX: ${GS_FILE_PREFIX:-testing}
      TG_WEBHOOK_PORT: ${TG_WEBHOOK_PORT:-8080}
      TG_TOKEN: ${TG_TOKEN}
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWD: ${MONGO_PASSWD}
      TG_WEBHOOK_URL: "ngork"

    container_name: bot
    restart: on-failure

