---
services:
  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    restart: on-failure
    environment:
      NGROK_AUTH: 1cceqE58nsQj71LTWWsKxFU2U6h_5L2ijaQRC2sD9n72vrn8E
      NGROK_PORT: bot:${TG_WEBHOOK_PORT}
      NGROK_DEBUG: 1
    ports:
      - 4040:4040

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ngrok
    env_file: ./.env
    ports:
        - ${TG_WEBHOOK_PORT}:${TG_WEBHOOK_PORT}

    container_name: bot
    restart: on-failure

